In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import cv2
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 200)


# =========================
# 1. 読み込み
# =========================

vod_title = "M8 vs. EDG - VALORANT Masters Santiago - SWISS"
video_path = Path(f"../../data/vods/{vod_title}.mp4")
csv_path = Path(f"../../data/processed/round_labels/{vod_title}_round_labels_fixed.csv")
df = pd.read_csv(csv_path)

print(df.shape)
display(df.head())
display(df.tail())

(45, 32)

,value,start_sec,end_sec,n_samples,mean_diff,min_diff,max_diff,duration_sec,t_sec,t_min,left_score,right_score,left_score_candidates,right_score_candidates,score_total,round_no_from_score,map_no,round_no,left_win_label,round_ocr_start_samples,round_ocr_end_samples,round_no_ocr_start,round_no_ocr_end,prev_round_no_ocr,prev_end_like,gap_from_prev,ocr_step,sequence_status,action_candidate,fix_applied,needs_review,map
0,True,9.009,78.078,70,22.858459,17.960205,26.488715,69.069,9.009,0.150150,0.0,0.0,"[0, 0, 0]","[0, 0, 0]",0.0,1.0,1,1,1.0,"[{'t_sec': 10.009, 'offset': 1.0, 'round_no': ...","[{'t_sec': 73.078, 'offset': -5.0, 'round_no':...",1,1,NaN,NaN,NaN,NaN,first,keep,NaN,False,HAVEN
1,True,106.106,203.203,98,23.621082,19.780490,27.049723,97.097,106.106,1.768433,1.0,0.0,"[1, 1, 1]","[0, 0, 0]",1.0,2.0,1,2,0.0,"[{'t_sec': 107.106, 'offset': 1.0, 'round_no':...","[{'t_sec': 198.203, 'offset': -5.0, 'round_no'...",2,2,1.0,78.078,28.028,1.0,ok,keep,NaN,False,HAVEN
2,True,235.235,278.278,44,25.698283,21.291341,27.700168,43.043,235.235,3.920583,1.0,1.0,"[1, 1, 1]","[1, 1, 1]",2.0,3.0,1,3,0.0,"[{'t_sec': 236.235, 'offset': 1.0, 'round_no':...","[{'t_sec': 273.278, 'offset': -5.0, 'round_no'...",3,3,2.0,203.203,32.032,1.0,ok,keep,NaN,False,HAVEN
3,True,297.297,390.390,94,25.161743,19.347548,27.986844,93.093,297.297,4.954950,1.0,2.0,"[1, 1, 1]","[2, 2, 2]",3.0,4.0,1,4,1.0,"[{'t_sec': 298.297, 'offset': 1.0, 'round_no':...","[{'t_sec': 385.39, 'offset': -5.0, 'round_no':...",4,4,3.0,278.278,19.019,1.0,ok,keep,NaN,False,HAVEN
4,True,421.421,515.515,95,23.683746,19.510579,27.125407,94.094,421.421,7.023683,2.0,2.0,"[2, 2, 2]","[2, 2, 2]",4.0,5.0,1,5,0.0,"[{'t_sec': 422.421, 'offset': 1.0, 'round_no':...","[{'t_sec': 510.515, 'offset': -5.0, 'round_no'...",5,5,4.0,390.390,31.031,1.0,ok,keep,NaN,False,HAVEN

,value,start_sec,end_sec,n_samples,mean_diff,min_diff,max_diff,duration_sec,t_sec,t_min,left_score,right_score,left_score_candidates,right_score_candidates,score_total,round_no_from_score,map_no,round_no,left_win_label,round_ocr_start_samples,round_ocr_end_samples,round_no_ocr_start,round_no_ocr_end,prev_round_no_ocr,prev_end_like,gap_from_prev,ocr_step,sequence_status,action_candidate,fix_applied,needs_review,map
40,True,5150.145,5252.247,103,18.012072,13.363254,21.365506,102.102,5150.145,85.835750,7.0,8.0,"[7, 7, 7]","[8, 8, 8]",15.0,16.0,2,17,0.0,"[{'t_sec': 5151.145, 'offset': 1.0, 'round_no'...","[{'t_sec': 5247.247, 'offset': -5.0, 'round_no...",16,16,15.0,5135.130,15.015,1.0,ok,keep,NaN,False,PEARL
41,True,5344.339,5435.430,92,18.075620,9.574761,24.011013,91.091,5344.339,89.072317,7.0,9.0,"[7, 7, 7]","[9, 9, 9]",16.0,17.0,2,18,0.0,"[{'t_sec': 5345.339, 'offset': 1.0, 'round_no'...","[{'t_sec': 5430.43, 'offset': -5.0, 'round_no'...",17,17,16.0,5252.247,92.092,1.0,ok,keep,NaN,False,PEARL
42,True,5469.464,5574.569,106,14.659329,10.677382,17.938368,105.105,5469.464,91.157733,7.0,10.0,"[7, 7, 7]","[10, 10, 10]",17.0,18.0,2,19,0.0,"[{'t_sec': 5470.464, 'offset': 1.0, 'round_no'...","[{'t_sec': 5569.569, 'offset': -5.0, 'round_no...",18,18,17.0,5435.430,34.034,1.0,ok,keep,NaN,False,PEARL
43,True,5679.674,5764.759,86,14.349154,9.363173,17.445123,85.085,5679.674,94.661233,7.0,11.0,"[7, 7, 7]","[11, 11, 11]",18.0,19.0,2,20,0.0,"[{'t_sec': 5680.674, 'offset': 1.0, 'round_no'...","[{'t_sec': 5759.759, 'offset': -5.0, 'round_no...",19,19,19.0,5607.602,72.072,0.0,drop_previous_candidate,drop_previous,drop_shorter_previous,False,PEARL
44,True,5796.791,5897.892,102,13.513559,9.481961,17.052979,101.101,5796.791,96.613183,7.0,12.0,"[7, 7, 7]","[12, 12, 12]",19.0,20.0,2,21,NaN,"[{'t_sec': 5797.791, 'offset': 1.0, 'round_no'...","[{'t_sec': 5892.892, 'offset': -5.0, 'round_no...",20,20,19.0,5764.759,32.032,1.0,ok,keep,NaN,False,PEARL

In [3]:
print(df.columns.tolist())

['value', 'start_sec', 'end_sec', 'n_samples', 'mean_diff', 'min_diff', 'max_diff', 'duration_sec', 't_sec', 't_min', 'left_score', 'right_score', 'left_score_candidates', 'right_score_candidates', 'score_total', 'round_no_from_score', 'map_no', 'round_no', 'left_win_label', 'round_ocr_start_samples', 'round_ocr_end_samples', 'round_no_ocr_start', 'round_no_ocr_end', 'prev_round_no_ocr', 'prev_end_like', 'gap_from_prev', 'ocr_step', 'sequence_status', 'action_candidate', 'fix_applied', 'needs_review', 'map', 'start_min']

In [2]:
df["start_min"] = df["start_sec"]/60

In [4]:
df[df["needs_review"]==True]

,value,start_sec,end_sec,n_samples,mean_diff,min_diff,max_diff,duration_sec,t_sec,t_min,left_score,right_score,left_score_candidates,right_score_candidates,score_total,round_no_from_score,map_no,round_no,left_win_label,round_ocr_start_samples,round_ocr_end_samples,round_no_ocr_start,round_no_ocr_end,prev_round_no_ocr,prev_end_like,gap_from_prev,ocr_step,sequence_status,action_candidate,fix_applied,needs_review,map,start_min
24,True,3242.239,3284.281,43,22.978553,18.324354,24.937337,42.042,3242.239,54.037317,0.0,0.0,"[0, 0, 0]","[0, 0, 0]",0.0,1.0,2,1,1.0,"[{'t_sec': 3243.239, 'offset': 1.0, 'round_no'...","[{'t_sec': 3279.281, 'offset': -5.0, 'round_no...",1,1,24.0,3229.226,13.013,-23.0,map_change_or_ocr_error,manual_check,manual_review_required,True,PEARL,54.037317
32,True,4055.051,4157.551,215,23.135734,18.097114,26.537435,102.500,4055.051,67.584183,5.0,3.0,"[5, 5, 5]","[3, 3, 3]",8.0,9.0,2,9,NaN,"[{'t_sec': 4056.051, 'offset': 1.0, 'round_no'...","[{'t_sec': 4264.265, 'offset': -5.0, 'round_no...",9,9,8.0,4025.021,30.030,1.0,split_round_transition,split,split_round_transition,True,PEARL,67.584183
33,True,4157.551,4269.265,215,23.135734,18.097114,26.537435,111.714,4157.551,69.292517,5.0,4.0,"[5, 5, 5]","[4, 4, 4]",9.0,10.0,2,10,NaN,"[{'t_sec': 4056.051, 'offset': 1.0, 'round_no'...","[{'t_sec': 4264.265, 'offset': -5.0, 'round_no...",10,10,9.0,4025.021,0.000,1.0,split_round_transition,split,split_round_transition,True,PEARL,69.292517
38,True,5022.017,5129.517,114,18.513291,13.944010,22.254150,107.500,5022.017,83.700283,7.0,7.0,"[7, 7, 7]","[7, 7, 7]",14.0,15.0,2,15,0.0,"[{'t_sec': 5023.017, 'offset': 1.0, 'round_no'...","[{'t_sec': 5130.13, 'offset': -5.0, 'round_no'...",15,15,14.0,4982.978,39.039,1.0,split_round_transition,split,split_round_transition,True,PEARL,83.700283
39,True,5129.517,5135.130,114,18.513291,13.944010,22.254150,5.613,5129.517,85.491950,7.0,8.0,"[7, 7, 7]","[8, 8, 8]",15.0,16.0,2,16,0.0,"[{'t_sec': 5023.017, 'offset': 1.0, 'round_no'...","[{'t_sec': 5130.13, 'offset': -5.0, 'round_no'...",16,16,15.0,4982.978,0.000,1.0,split_round_transition,split,split_round_transition,True,PEARL,85.491950

In [5]:
df[["start_min",'start_sec', 'end_sec', 'duration_sec', 'left_score', 'right_score','round_no_from_score', 'round_no_ocr_start', 'round_no_ocr_end']]

    start_min  start_sec   end_sec  duration_sec  left_score  right_score  round_no_from_score  round_no_ocr_start  round_no_ocr_end
0    0.150150      9.009    78.078        69.069         0.0          0.0                  1.0                   1                 1
1    1.768433    106.106   203.203        97.097         1.0          0.0                  2.0                   2                 2
2    3.920583    235.235   278.278        43.043         1.0          1.0                  3.0                   3                 3
3    4.954950    297.297   390.390        93.093         1.0          2.0                  4.0                   4                 4
4    7.023683    421.421   515.515        94.094         2.0          2.0                  5.0                   5                 5
5    9.042367    542.542   650.650       108.108         2.0          3.0                  6.0                   6                 6
6   12.278933    736.736   862.862       126.126         2.0          4.0                  7.0                   7                 7
7   14.931583    895.895   972.972        77.077         2.0          5.0                  8.0                   8                 8
8   16.533183    991.991  1148.147       156.156         2.0          6.0                  9.0                   9                 9
9   19.502817   1170.169  1262.261        92.092         2.0          7.0                 10.0                  10                10
10  21.688333   1301.300  1382.381        81.081         3.0          7.0                 11.0                  11                11
11  23.690333   1421.420  1474.473        53.053         4.0          7.0                 12.0                  12                12
12  26.960267   1617.616  1688.687        71.071         4.0          8.0                 13.0                  13                13
13  28.578550   1714.713  1793.792        79.079         4.0          9.0                 14.0                  14                14
14  30.246883   1814.813  1919.918       105.105         4.0         10.0                 15.0                  15                15
15  32.499133   1949.948  2067.065       117.117         5.0         10.0                 16.0                  16                16
16  35.885850   2153.151  2225.223        72.072         6.0         10.0                 17.0                  17                17
17  37.404033   2244.242  2338.336        94.094         7.0         10.0                 18.0                  18                18
18  39.472767   2368.366  2420.418        52.052         8.0         10.0                 19.0                  19                19
19  40.857483   2451.449  2574.572       123.123         9.0         10.0                 20.0                  20                20
20  44.427717   2665.663  2771.769       106.106        10.0         10.0                 21.0                  21                21
21  46.596550   2795.793  2885.883        90.090        10.0         11.0                 22.0                  22                22
22  49.766383   2985.983  3099.096       113.113        10.0         12.0                 23.0                  23                23
23  52.085367   3125.122  3229.226       104.104        11.0         12.0                 24.0                  24                24
24  54.037317   3242.239  3284.281        42.042         0.0          0.0                  1.0                   1                 1
25  55.221833   3313.310  3372.369        59.059         1.0          0.0                  2.0                   2                 2
26  56.639917   3398.395  3486.483        88.088         2.0          0.0                  3.0                   3                 3
27  58.458400   3507.504  3564.561        57.057         2.0          1.0                  4.0                   4                 4
28  59.893167   3593.590  3704.701       111.111         2.0          2.0                  5.0                   5                 5
29  62.212150   3732.729  3801.798        69.069         3.0          2.0                  6.0                   6                 6
30  63.880483   3832.829  3940.937       108.108         3.0          3.0                  7.0                   7                 7
31  66.182783   3970.967  4025.021        54.054         4.0          3.0                  8.0                   8                 8
32  67.584183   4055.051  4157.551       102.500         5.0          3.0                  9.0                   9                 9
33  69.292517   4157.551  4269.265       111.714         5.0          4.0                 10.0                  10                10
34  72.639233   4358.354  4489.485       131.131         6.0          4.0                 11.0                  11                11
35  75.075000   4504.500  4561.557        57.057         6.0          5.0                 12.0                  12                12
36  78.461717   4707.703  4846.842       139.139         6.0          6.0                 13.0                  13                13
37  81.331250   4879.875  4982.978       103.103         7.0          6.0                 14.0                  14                14
38  83.700283   5022.017  5129.517       107.500         7.0          7.0                 15.0                  15                15
39  85.491950   5129.517  5135.130         5.613         7.0          8.0                 16.0                  16                16
40  85.835750   5150.145  5252.247       102.102         7.0          8.0                 16.0                  16                16
41  89.072317   5344.339  5435.430        91.091         7.0          9.0                 17.0                  17                17
42  91.157733   5469.464  5574.569       105.105         7.0         10.0                 18.0                  18                18
43  94.661233   5679.674  5764.759        85.085         7.0         11.0                 19.0                  19                19
44  96.613183   5796.791  5897.892       101.101         7.0         12.0                 20.0                  20                20

In [19]:
df

,value,start_sec,end_sec,n_samples,mean_diff,min_diff,max_diff,duration_sec,t_sec,t_min,left_score,right_score,left_score_candidates,right_score_candidates,score_total,round_no_from_score,map_no,round_no,left_win_label,round_ocr_start_samples,round_ocr_end_samples,round_no_ocr_start,round_no_ocr_end,prev_round_no_ocr,prev_end_like,gap_from_prev,ocr_step,sequence_status,action_candidate,fix_applied,needs_review,map,start_min
0,True,9.009,78.078,70,22.858459,17.960205,26.488715,69.069,9.009,0.150150,0,0,"[0, 0, 0]","[0, 0, 0]",0,1,1,1,1.0,"[{'t_sec': 10.009, 'offset': 1.0, 'round_no': ...","[{'t_sec': 73.078, 'offset': -5.0, 'round_no':...",1,1,NaN,NaN,NaN,NaN,first,keep,NaN,False,HAVEN,0.150150
1,True,106.106,203.203,98,23.621082,19.780490,27.049723,97.097,106.106,1.768433,1,0,"[1, 1, 1]","[0, 0, 0]",1,2,1,2,0.0,"[{'t_sec': 107.106, 'offset': 1.0, 'round_no':...","[{'t_sec': 198.203, 'offset': -5.0, 'round_no'...",2,2,1.0,78.078,28.028,1.0,ok,keep,NaN,False,HAVEN,1.768433
2,True,235.235,278.278,44,25.698283,21.291341,27.700168,43.043,235.235,3.920583,1,1,"[1, 1, 1]","[1, 1, 1]",2,3,1,3,0.0,"[{'t_sec': 236.235, 'offset': 1.0, 'round_no':...","[{'t_sec': 273.278, 'offset': -5.0, 'round_no'...",3,3,2.0,203.203,32.032,1.0,ok,keep,NaN,False,HAVEN,3.920583
3,True,297.297,390.390,94,25.161743,19.347548,27.986844,93.093,297.297,4.954950,1,2,"[1, 1, 1]","[2, 2, 2]",3,4,1,4,1.0,"[{'t_sec': 298.297, 'offset': 1.0, 'round_no':...","[{'t_sec': 385.39, 'offset': -5.0, 'round_no':...",4,4,3.0,278.278,19.019,1.0,ok,keep,NaN,False,HAVEN,4.954950
4,True,421.421,515.515,95,23.683746,19.510579,27.125407,94.094,421.421,7.023683,2,2,"[2, 2, 2]","[2, 2, 2]",4,5,1,5,0.0,"[{'t_sec': 422.421, 'offset': 1.0, 'round_no':...","[{'t_sec': 510.515, 'offset': -5.0, 'round_no'...",5,5,4.0,390.390,31.031,1.0,ok,keep,NaN,False,HAVEN,7.023683
5,True,542.542,650.650,109,23.825269,19.197130,27.194607,108.108,542.542,9.042367,2,3,"[2, 2, 2]","[3, 3, 3]",5,6,1,6,0.0,"[{'t_sec': 543.542, 'offset': 1.0, 'round_no':...","[{'t_sec': 645.65, 'offset': -5.0, 'round_no':...",6,6,5.0,515.515,27.027,1.0,ok,keep,NaN,False,HAVEN,9.042367
6,True,736.736,862.862,127,24.199966,18.810683,27.099338,126.126,736.736,12.278933,2,4,"[2, 2, 2]","[4, 4, 4]",6,7,1,7,0.0,"[{'t_sec': 737.736, 'offset': 1.0, 'round_no':...","[{'t_sec': 857.862, 'offset': -5.0, 'round_no'...",7,7,6.0,650.650,86.086,1.0,ok,keep,NaN,False,HAVEN,12.278933
7,True,895.895,972.972,78,25.151095,18.837484,26.630968,77.077,895.895,14.931583,2,5,"[2, 2, 2]","[5, 5, 5]",7,8,1,8,0.0,"[{'t_sec': 896.895, 'offset': 1.0, 'round_no':...","[{'t_sec': 967.972, 'offset': -5.0, 'round_no'...",8,8,7.0,862.862,33.033,1.0,ok,keep,NaN,False,HAVEN,14.931583
8,True,991.991,1148.147,157,23.723775,18.561252,27.512126,156.156,991.991,16.533183,2,6,"[2, 2, 2]","[6, 6, 6]",8,9,1,9,0.0,"[{'t_sec': 992.991, 'offset': 1.0, 'round_no':...","[{'t_sec': 1143.147, 'offset': -5.0, 'round_no...",9,9,8.0,972.972,19.019,1.0,ok,keep,NaN,False,HAVEN,16.533183
9,True,1170.169,1262.261,93,21.988577,18.152751,26.461480,92.092,1170.169,19.502817,2,7,"[2, 2, 2]","[7, 7, 7]",9,10,1,10,1.0,"[{'t_sec': 1171.169, 'offset': 1.0, 'round_no'...","[{'t_sec': 1257.261, 'offset': -5.0, 'round_no...",10,10,9.0,1148.147,22.022,1.0,ok,keep,NaN,False,HAVEN,19.502817
10,True,1301.300,1382.381,82,22.366953,18.454508,25.489990,81.081,1301.300,21.688333,3,7,"[3, 3, 3]","[7, 7, 7]",10,11,1,11,1.0,"[{'t_sec': 1302.3, 'offset': 1.0, 'round_no': ...","[{'t_sec': 1377.381, 'offset': -5.0, 'round_no...",11,11,10.0,1262.261,39.039,1.0,ok,keep,NaN,False,HAVEN,21.688333
11,True,1421.420,1474.473,54,24.010652,17.926649,25.997179,53.053,1421.420,23.690333,4,7,"[4, 4, 4]","[7, 7, 7]",11,12,1,12,0.0,"[{'t_sec': 1422.42, 'offset': 1.0, 'round_no':...","[{'t_sec': 1469.473, 'offset': -5.0, 'round_no...",12,12,11.0,1382.381,39.039,1.0,ok,keep,NaN,False,HAVEN,23.690333
12,True,1617.616,1688.687,72,18.887600,13.990343,21.627143,71.071,1617.616,26.960267,4,8,"[4, 4, 4]","[8, 8, 8]",12,13,1,13,0.0,"[{'t_sec': 1618.616, 'offset': 1.0, 'round_no'...","[{'t_sec': 1683.687, 'offset': -5.0, 'round_no...",13,13,12.0,1474.473,143.143,1.0,ok,keep,NaN,False,HAVEN,26.960267
13,True,1714.713,1793.792,80,17.993038,11.686578,21.487576,79.079,1714.713,28.578550,4,9,"[4, 4, 4]","[9, 9, 9]",13,14,1,14,0.0,"[{'t_sec': 1715.713, 'offset': 1.0, 'round_no'...","[{'t_sec': 1788.792, 'offset': -5.0, 'round_no...",14,14,13.0,1688.687,26.026,1.0,ok,keep,NaN,False,HAVEN,28.578550
14,True,1814.813,1919.918,106,14.546125,9.996474,17.822971,105.105,1814.813,30.246883,4,10,"[4, 4, 4]","[10, 10, 10]",14,15,1,15,1.0,"[{'t_sec': 1815.813, 'offset': 1.0, 'round_no'...","[{'t_sec': 1914.918, 'offset': -5.0, 'round_no...",15,15,14.0,1793.792,21.021,1.0,ok,keep,NaN,False,HAVEN,30.246883
15,True,1949.948,2067.065,118,15.365243,10.844835,18.269233,117.117,1949.948,32.499133,5,10,"[5, 5, 5]","[10, 10, 10]",15,16,1,16,1.0,"[{'t_sec': 1950.948, 'offset': 1.0, 'round_no'...","[{'t_sec': 2062.065, 'offset': -5.0, 'round_no...",16,16,15.0,1919.918,30.030,1.0,ok,keep,NaN,False,HAVEN,32.499133
16,True,2153.151,2225.223,73,15.355140,9.336426,18.829074,72.072,2153.151,35.885850,6,10,"[6, 6, 6]","[10, 10, 10]",16,17,1,17,1.0,"[{'t_sec': 2154.151, 'offset': 1.0, 'round_no'...","[{'t_sec': 2220.223, 'offset': -5.0, 'round_no...",17,17,16.0,2067.065,86.086,1.0,ok,keep,NaN,False,HAVEN,35.885850
17,True,2244.242,2338.336,95,15.164330,10.035211,18.863905,94.094,2244.242,37.404033,7,10,"[7, 7, 7]","[10, 10, 10]",17,18,1,18,1.0,"[{'t_sec': 2245.242, 'offset': 1.0, 'round_no'...","[{'t_sec': 2333.336, 'offset': -5.0, 'round_no...",18,18,17.0,2225.223,19.019,1.0,ok,keep,NaN,False,HAVEN,37.404033
18,True,2368.366,2420.418,53,14.907016,9.344672,17.749295,52.052,2368.366,39.472767,8,10,"[8, 8, 8]","[10, 10, 10]",18,19,1,19,1.0,"[{'t_sec': 2369.366, 'offset': 1.0, 'round_no'...","[{'t_sec': 2415.418, 'offset': -5.0, 'round_no...",19,19,18.0,2338.336,30.030,1.0,ok,keep,NaN,False,HAVEN,39.472767
19,True,2451.449,2574.572,124,14.993425,5.611410,18.347873,123.123,2451.449,40.857483,9,10,"[9, 9, 9]","[10, 10, 10]",19,20,1,20,1.0,"[{'t_sec': 2452.449, 'offset': 1.0, 'round_no'...","[{'t_sec': 2569.572, 'offset': -5.0, 'round_no...",20,20,19.0,2420.418,31.031,1.0,ok,keep,NaN,False,HAVEN,40.857483
20,True,2665.663,2771.769,107,8.740486,4.437717,15.958550,106.106,2665.663,44.427717,10,10,"[10, 10, 10]","[10, 10, 10]",20,21,1,21,0.0,"[{'t_sec': 2666.663, 'offset': 1.0, 'round_no'...","[{'t_sec': 2766.769, 'offset': -5.0, 'round_no...",21,21,20.0,2574.572,91.091,1.0,ok,keep,NaN,False,HAVEN,44.427717
21,True,2795.793,2885.883,91,10.842537,5.859809,14.472168,90.090,2795.793,46.596550,10,11,"[10, 10, 10]","[11, 11, 11]",21,22,1,22,0.0,"[{'t_sec': 2796.793, 'offset': 1.0, 'round_no'...","[{'t_sec': 2880.8830000000003, 'offset': -5.0,...",22,22,21.0,2771.769,24.024,1.0,ok,keep,NaN,False,HAVEN,46.596550
22,True,2985.983,3099.096,114,8.940411,0.000000,13.375597,113.113,2985.983,49.766383,10,12,"[10, 10, 10]","[12, 12, 12]",22,23,1,23,1.0,"[{'t_sec': 2986.983, 'offset': 1.0, 'round_no'...","[{'t_sec': 3094.096, 'offset': -5.0, 'round_no...",23,23,22.0,2885.883,100.100,1.0,ok,keep,NaN,False,HAVEN,49.766383
23,True,3125.122,3229.226,105,10.462846,6.556424,14.429742,104.104,3125.122,52.085367,11,12,"[11, 11, 11]","[12, 12, 12]",23,24,1,24,NaN,"[{'t_sec': 3126.122, 'offset': 1.0, 'round_no'...","[{'t_sec': 3224.226, 'offset': -5.0, 'round_no...",24,24,23.0,3099.096,26.026,1.0,ok,keep,NaN,False,HAVEN,52.085367
24,True,3242.239,3284.281,43,22.978553,18.324354,24.937337,42.042,3242.239,54.037317,0,0,"[0, 0, 0]","[0, 0, 0]",0,1,2,1,1.0,"[{'t_sec': 3243.239, 'offset': 1.0, 'round_no'...","[{'t_sec': 3279.281, 'offset': -5.0, 'round_no...",1,1,24.0,3229.226,13.013,-23.0,map_change_or_ocr_error,manual_check,manual_review_required,True,PEARL,54.037317
25,True,3313.310,3372.369,60,23.372730,18.725016,26.152425,59.059,3313.310,55.221833,1,0,"[1, 1, 1]","[0, 0, 0]",1,2,2,2,1.0,"[{'t_sec': 3314.31, 'offset': 1.0, 'round_no':...","[{'t_sec': 3367.369, 'offset': -5.0, 'round_no...",2,2,1.0,3284.281,29.029,1.0,ok,keep,NaN,False,PEARL,55.221833
26,True,3398.395,3486.483,89,23.503907,19.120904,26.315728,88.088,3398.395,56.639917,2,0,"[2, 2, 2]","[0, 0, 0]",2,3,2,3,0.0,"[{'t_sec': 3399.395, 'offset': 1.0, 'round_no'...","[{'t_sec': 3481.483, 'offset': -5.0, 'round_no...",3,3,2.0,3372.369,26.026,1.0,ok,keep,NaN,False,PEARL,56.639917
27,True,3507.504,3564.561,58,25.188809,18.771539,27.473606,57.057,3507.504,58.458400,2,1,"[2, 2, 2]","[1, 1, 1]",3,4,2,4,0.0,"[{'t_sec': 3508.504, 'offset': 1.0, 'round_no'...","[{'t_sec': 3559.561, 'offset': -5.0, 'round_no...",4,4,3.0,3486.483,21.021,1.0,ok,keep,NaN,False,PEARL,58.458400
28,True,3593.590,3704.701,112,23.446161,18.530002,26.867052,111.111,3593.590,59.893167,2,2,"[2, 2, 2]","[2, 2, 2]",4,5,2,5,1.0,"[{'t_sec': 3594.59, 'offset': 1.0, 'round_no':...","[{'t_sec': 3699.701, 'offset': -5.0, 'round_no...",5,5,4.0,3564.561,29.029,1.0,ok,keep,NaN,False,PEARL,59.893167
29,True,3732.729,3801.798,70,23.863802,18.407444,26.390978,69.069,3732.729,62.212150,3,2,"[3, 3, 3]","[2, 2, 2]",5,6,2,6,0.0,"[{'t_sec': 3733.729, 'offset': 1.0, 'round_no'...","[{'t_sec': 3796.798, 'offset': -5.0, 'round_no...",6,6,5.0,3704.701,28.028,1.0,ok,keep,NaN,False,PEARL,62.212150
30,True,3832.829,3940.937,109,22.810702,18.564914,26.491157,108.108,3832.829,63.880483,3,3,"[3, 3, 3]","[3, 3, 3]",6,7,2,7,1.0,"[{'t_sec': 3833.829, 'offset': 1.0, 'round_no'...","[{'t_sec': 3935.937, 'offset': -5.0, 'round_no...",7,7,6.0,3801.798,31.031,1.0,ok,keep,NaN,False,PEARL,63.880483
31,True,3970.967,4025.021,55,25.429773,22.122803,26.820150,54.054,3970.967,66.182783,4,3,"[4, 4, 4]","[3, 3, 3]",7,8,2,8,1.0,"[{'t_sec': 3971.967, 'offset': 1.0, 'round_no'...","[{'t_sec': 4020.021, 'offset': -5.0, 'round_no...",8,8,7.0,3940.937,30.030,1.0,ok,keep,NaN,False,PEARL,66.182783
32,True,4055.051,4157.551,215,23.135734,18.097114,26.537435,102.500,4055.051,67.584183,5,3,"[5, 5, 5]","[3, 3, 3]",8,9,2,9,NaN,"[{'t_sec': 4056.051, 'offset': 1.0, 'round_no'...","[{'t_sec': 4264.265, 'offset': -5.0, 'round_no...",9,9,8.0,4025.021,30.030,1.0,split_round_transition,split,split_round_transition,True,PEARL,67.584183
33,True,4157.551,4269.265,215,23.135734,18.097114,26.537435,111.714,4055.051,67.584183,5,3,"[5, 5, 5]","[3, 3, 3]",8,9,2,10,NaN,"[{'t_sec': 4056.051, 'offset': 1.0, 'round_no'...","[{'t_sec': 4264.265, 'offset': -5.0, 'round_no...",10,10,9.0,4025.021,0.000,1.0,split_round_transition,split,split_round_transition,True,PEARL,69.292517
34,True,4358.354,4489.485,132,23.180901,17.496799,26.116753,131.131,4358.354,72.639233,6,4,"[6, 6, 6]","[4, 4, 4]",10,11,2,11,0.0,"[{'t_sec': 4359.354, 'offset': 1.0, 'round_no'...","[{'t_sec': 4484.485, 'offset': -5.0, 'round_no...",11,11,9.0,4269.265,89.089,2.0,missing_round_between,inspect_between,NaN,False,PEARL,72.639233
35,True,4504.500,4561.557,58,23.370151,17.684543,25.726264,57.057,4504.500,75.075000,6,5,"[6, 6, 6]","[5, 5, 5]",11,12,2,12,0.0,"[{'t_sec': 4505.5, 'offset': 1.0, 'round_no': ...","[{'t_sec': 4556.557, 'offset': -5.0, 'round_no...",12,12,11.0,4489.485,15.015,1.0,ok,keep,NaN,False,PEARL,75.075000
36,True,4707.703,4846.842,140,18.290755,13.263672,24.383599,139.139,4707.703,78.461717,6,6,"[6, 6, 6]","[None, 6, 6]",12,13,2,13,1.0,"[{'t_sec': 4708.703, 'offset': 1.0, 'round_no'...","[{'t_sec': 4841.842, 'offset': -5.0, 'round_no...",13,13,12.0,4561.557,146.146,1.0,ok,keep,NaN,False,PEARL,78.461717
37,True,4879.875,4982.978,104,19.131508,14.604628,21.955322,103.103,4879.875,81.331250,7,6,"[7, 7, 7]","[6, 6, 6]",13,14,2,14,0.0,"[{'t_sec': 4880.875, 'offset': 1.0, 'round_no'...","[{'t_sec': 4977.978, 'offset': -5.0, 'round_no...",14,14,13.0,4846.842,33.033,1.0,ok,keep,NaN,False,PEARL,81.331250
38,True,5022.017,5129.517,114,18.513291,13.944010,22.254150,107.500,5022.017,83.700283,7,7,"[7, 7, 7]","[7, 7, 7]",14,15,2,15,0.0,"[{'t_sec': 5023.017, 'offset': 1.0, 'round_no'...","[{'t_sec': 5130.13, 'offset': -5.0, 'round_no'...",15,15,14.0,4982.978,39.039,1.0,split_round_transition,split,split_round_transition,True,PEARL,83.700283
39,True,5129.517,5135.130,114,18.513291,13.944010,22.254150,5.613,5022.017,83.700283,7,7,"[7, 7, 7]","[7, 7, 7]",14,15,2,16,0.0,"[{'t_sec': 5023.017, 'offset': 1.0, 'round_no'...","[{'t_sec': 5130.13, 'offset': -5.0, 'round_no'...",16,16,15.0,4982.978,0.000,1.0,split_round_transition,split,split_round_transition,True,PEARL,85.491950
40,True,5150.145,5252.247,103,18.012072,13.363254,21.365506,102.102,5150.145,85.835750,7,8,"[7, 7, 7]","[8, 8, 8]",15,16,2,17,0.0,"[{'t_sec': 5151.145, 'offset': 1.0, 'round_no'...","[{'t_sec': 5247.247, 'offset': -5.0, 'round_no...",16,16,15.0,5135.130,15.015,1.0,ok,keep,NaN,False,PEARL,85.835750
41,True,5344.339,5435.430,92,18.075620,9.574761,24.011013,91.091,5344.339,89.072317,7,9,"[7, 7, 7]","[9, 9, 9]",16,17,2,18,0.0,"[{'t_sec': 5345.339, 'offset': 1.0, 'round_no'...","[{'t_sec': 5430.43, 'offset': -5.0, 'round_no'...",17,17,16.0,5252.247,92.092,1.0,ok,keep,NaN,False,PEARL,89.072317
42,True,5469.464,5574.569,106,14.659329,10.677382,17.938368,105.105,5469.464,91.157733,7,10,"[7, 7, 7]","[10, 10, 10]",17,18,2,19,0.0,"[{'t_sec': 5470.464, 'offset': 1.0, 'round_no'...","[{'t_sec': 5569.569, 'offset': -5.0, 'round_no...",18,18,17.0,5435.430,34.034,1.0,ok,keep,NaN,False,PEARL,91.157733
43,True,5679.674,5764.759,86,14.349154,9.363173,17.445123,85.085,5679.674,94.661233,7,11,"[7, 7, 7]","[11, 11, 11]",18,19,2,20,0.0,"[{'t_sec': 5680.674, 'offset': 1.0, 'round_no'...","[{'t_sec': 5759.759, 'offset': -5.0, 'round_no...",19,19,19.0,5607.602,72.072,0.0,drop_previous_candidate,drop_previous,drop_shorter_previous,False,PEARL,94.661233
44,True,5796.791,5897.892,102,13.513559,9.481961,17.052979,101.101,5796.791,96.613183,7,12,"[7, 7, 7]","[12, 12, 12]",19,20,2,21,NaN,"[{'t_sec': 5797.791, 'offset': 1.0, 'round_no'...","[{'t_sec': 5892.892, 'offset': -5.0, 'round_no...",20,20,19.0,5764.759,32.032,1.0,ok,keep,NaN,False,PEARL,96.613183